# Generated by Django 5.0.1 on 2024-01-30 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_review', models.IntegerField(null=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=150)),
                ('location_review', models.IntegerField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.fishing_area')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.fishing_method')),
            ],
        ),
    ]
