# Generated by Django 4.2.9 on 2024-01-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField()),
                ('schedule_location', models.CharField(max_length=200)),
                ('schedule_fishing_method', models.CharField(max_length=20)),
                ('schedule_fishing_Area', models.CharField(max_length=20)),
            ],
        ),
    ]
