# Generated by Django 4.2.9 on 2024-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_done',
            field=models.BooleanField(default=False),
        ),
    ]
