# Generated by Django 5.0.1 on 2024-01-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_schedule_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_done',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_fishing_Area',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_fishing_method',
        ),
    ]
