# Generated by Django 5.0.1 on 2024-01-23 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
        ('schedule', '0003_rename_schedule_date_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.fishing_area'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='method_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.fising_method'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
