# Generated by Django 5.0.1 on 2024-02-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presurvey',
            field=models.BooleanField(default=False),
        ),
    ]
