# Generated by Django 5.0.1 on 2024-01-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fishing_area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('document', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fishing_bait',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('document', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fishing_equipment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('document', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fising_method',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('document', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='prohibit_fish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_kor', models.CharField(max_length=40)),
                ('name_end', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_start', models.DateField()),
                ('standard_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='release_fish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_kor', models.CharField(max_length=40)),
                ('name_end', models.CharField(blank=True, max_length=50, null=True)),
                ('standard', models.FloatField()),
            ],
        ),
    ]
