# Generated by Django 5.0.1 on 2024-01-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_fish',
            name='max_length',
            field=models.FloatField(default=0),
        ),
    ]
