# Generated by Django 5.0.1 on 2024-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lattitude',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(max_length=30),
        ),
    ]
